import type { ProductWithCounts, Comment, Profile } from "@/types/database";

export const MOCK_PROFILES: Profile[] = [
  {
    id: "1",
    display_name: "Sahar",
    handle: "saharpk",
    avatar_url: null,
    bio: "Building productbuilders.app",
    is_admin: true,
    created_at: "2026-05-01T00:00:00Z",
  },
  {
    id: "2",
    display_name: "Daniel",
    handle: "danieldev",
    avatar_url: null,
    bio: "Full-stack dev who ships fast",
    is_admin: false,
    created_at: "2026-05-03T00:00:00Z",
  },
  {
    id: "3",
    display_name: "Rita",
    handle: "roaming_rita",
    avatar_url: null,
    bio: "Designer turned builder",
    is_admin: false,
    created_at: "2026-05-05T00:00:00Z",
  },
  {
    id: "4",
    display_name: "Jake",
    handle: "jakebuilds",
    avatar_url: null,
    bio: "Shipping side projects every month",
    is_admin: false,
    created_at: "2026-05-07T00:00:00Z",
  },
  {
    id: "5",
    display_name: "Mina",
    handle: "cookwithcode",
    avatar_url: null,
    bio: "Food + tech = my thing",
    is_admin: false,
    created_at: "2026-05-08T00:00:00Z",
  },
];

export const MOCK_PRODUCTS: ProductWithCounts[] = [
  {
    id: "p1",
    builder_id: "1",
    name: "PlantPal",
    tagline: "AI plant care buddy that knows what your plants need.",
    description:
      "Take a photo of your plant, and PlantPal identifies it, diagnoses issues, and gives you a personalized care schedule. Works offline after the first scan. Built with Claude vision API and a custom plant database.",
    url: "https://plantpal.app",
    image_url: null,
    category: "AI",
    stage: "idea",
    status: "live",
    week_of: "2026-05-12",
    created_at: "2026-05-13T10:00:00Z",
    vote_count: 31,
    comment_count: 12,
    builder: { display_name: "Sahar", handle: "saharpk", avatar_url: null },
  },
  {
    id: "p2",
    builder_id: "2",
    name: "Snippet Studio",
    tagline: "Organize, share and sync your code snippets effortlessly.",
    description:
      "A beautiful snippet manager that syncs across VS Code, Cursor, and the web. Tag, search, and share snippets with your team. Markdown preview built in.",
    url: "https://snippetstudio.dev",
    image_url: null,
    category: "Developer Tool",
    stage: "building",
    status: "live",
    week_of: "2026-05-12",
    created_at: "2026-05-12T14:00:00Z",
    vote_count: 68,
    comment_count: 23,
    builder: { display_name: "Daniel", handle: "danieldev", avatar_url: null },
    user_has_voted: true,
  },
  {
    id: "p3",
    builder_id: "3",
    name: "TrailLog",
    tagline: "Beautiful hiking journal to remember every trail.",
    description:
      "Log your hikes with GPS tracks, photos, and notes. TrailLog creates a beautiful timeline of your outdoor adventures. Export as a photo book.",
    url: "https://traillog.io",
    image_url: null,
    category: "Web App",
    stage: "launched",
    status: "live",
    week_of: "2026-05-12",
    created_at: "2026-05-14T09:00:00Z",
    vote_count: 42,
    comment_count: 15,
    builder: {
      display_name: "Rita",
      handle: "roaming_rita",
      avatar_url: null,
    },
  },
  {
    id: "p4",
    builder_id: "5",
    name: "MealMind",
    tagline: "Meal planning that learns your taste and budget.",
    description:
      "Tell MealMind what you like, your budget, and dietary needs. It generates a weekly meal plan with a grocery list. Gets smarter every week.",
    url: null,
    image_url: null,
    category: "Mobile",
    stage: "building",
    status: "live",
    week_of: "2026-05-12",
    created_at: "2026-05-15T11:00:00Z",
    vote_count: 19,
    comment_count: 8,
    builder: {
      display_name: "Mina",
      handle: "cookwithcode",
      avatar_url: null,
    },
  },
  {
    id: "p5",
    builder_id: "4",
    name: "DevPulse",
    tagline: "Daily standup summaries powered by your git commits.",
    description:
      "Connects to your GitHub/GitLab, reads your commits and PRs, and writes a standup update for you. Saves 5 minutes every morning.",
    url: null,
    image_url: null,
    category: "Developer Tool",
    stage: "idea",
    status: "live",
    week_of: "2026-05-12",
    created_at: "2026-05-16T08:00:00Z",
    vote_count: 11,
    comment_count: 5,
    builder: {
      display_name: "Jake",
      handle: "jakebuilds",
      avatar_url: null,
    },
  },
];

export const MOCK_COMMENTS: Record<string, Comment[]> = {
  p1: [
    {
      id: "c1",
      product_id: "p1",
      author_id: "2",
      body: "Love this idea! I kill every plant I own. Would definitely use this.",
      status: "live",
      created_at: "2026-05-13T12:00:00Z",
      author: { display_name: "Daniel", handle: "danieldev", avatar_url: null },
    },
    {
      id: "c2",
      product_id: "p1",
      author_id: "3",
      body: "Have you looked at the PlantNet API? Could save you building the identification model from scratch.",
      status: "live",
      created_at: "2026-05-13T15:30:00Z",
      author: { display_name: "Rita", handle: "roaming_rita", avatar_url: null },
    },
    {
      id: "c3",
      product_id: "p1",
      author_id: "4",
      body: "The offline-first approach is smart. Most plant apps need internet which is useless when you're in the garden.",
      status: "live",
      created_at: "2026-05-14T09:00:00Z",
      author: { display_name: "Jake", handle: "jakebuilds", avatar_url: null },
    },
  ],
  p2: [
    {
      id: "c4",
      product_id: "p2",
      author_id: "1",
      body: "This is exactly what I've been looking for. The VS Code sync is a killer feature.",
      status: "live",
      created_at: "2026-05-12T16:00:00Z",
      author: { display_name: "Sahar", handle: "saharpk", avatar_url: null },
    },
    {
      id: "c5",
      product_id: "p2",
      author_id: "4",
      body: "How does it handle conflicts when editing the same snippet on two machines?",
      status: "live",
      created_at: "2026-05-13T10:00:00Z",
      author: { display_name: "Jake", handle: "jakebuilds", avatar_url: null },
    },
  ],
};

export function isMockMode(): boolean {
  const url = process.env.NEXT_PUBLIC_SUPABASE_URL ?? "";
  return !url || url.includes("placeholder") || url.includes("example");
}
